// 11/09/2020 EASY

// https://leetcode-cn.com/problems/find-the-difference/

/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.

 */

function findTheDifference(s: string, t: string): string {
  const charArr: number[] = new Array(26).fill(0);
  let indexS = 0, indexT = 0;
  while (indexS < s.length || indexT < t.length) {
    if (indexS < s.length) {
      const charIndex = s[indexS].charCodeAt(0) - "a".charCodeAt(0);
      charArr[charIndex]--;
      indexS++;
    }
    if (indexT < t.length) {
      const charIndex = t[indexT].charCodeAt(0) - "a".charCodeAt(0);
      charArr[charIndex]++;
      indexT++;
    }
  }
  return String.fromCharCode("a".charCodeAt(0) + charArr.findIndex(item => item > 0))
};
